### ISSUE TITLE
Pressing F1 Does Not Hide the Text From Screen (again)

### ISSUE THREAD

**Issue by UnknownSerhan** [lanAnderson/SeasonInfo#101]
**Describe the issue**

- Duplicate of https://github.com/lanAnderson/SeasonHUD/issues/95, it seems it is still happening.

**Minecraft Version**

- 1.21.

**Mod Version**

- 1.9.7

**Modloader(Fabric/Forge/NeoForge)**

- NeoForge

**Modloader Version**

- 20.0.143

**Additional Info (Crashlog/Modlist)**

- Journeymap is installed (6.0.0-beta.18)

![image](https://github.com/user-attachments/assets/5e4262ee-165e-4a2b-8800-950c332a9a16)

**Comment by lanAnderson** [comment]
Should be fixed in v1.9.8
