### ISSUE TITLE
Could not execute entrypoint stage 'client' due to errors, provided by 'seasonhud'

### ISSUE THREAD

**Issue by EightEggs** [lanAnderson/SeasonInfo#102]
**Describe the issue**

I guess there is something wrong with `nightconfig`

```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'seasonhud'

......

com.electronwill.nightconfig.core.io.WritingMode does not have member field 'com.electronwill.nightconfig.core.io.WritingMode REPLACE_ATOMIC'
```

**Minecraft Version**

1.21

**Mod Version**

1.9.8

**Modloader(Fabric/Forge/NeoForge)**

Fabric 0.16.0

**Additional Info (Crashlog/Modlist)**

[crash_report.txt](https://github.com/user-attachments/files/16478785/crash-2024-08-03_16.49.43-client.txt)

[latest.log](https://github.com/user-attachments/files/16478788/latest.log)

**Comment by EightEggs** [comment]
idk why but, downgrading `Forge Config API Port` from v21.0.7 to v21.0.1 solved this.

**Comment by lanAnderson** [comment]
https://github.com/Fuzss/forgeconfigapiport/issues/65#issuecomment-2266716863
