### ISSUE TITLE
Entering a 1.16.5 server with FTB Chunk a second time will crash the game

### ISSUE THREAD

**Issue by panda-lsy** [lanAnderson/SeasonInfo#103]
**Describe the issue**

Entering a server with FTB Chunk a second time will crash the game

**Minecraft Version**

1.16.5

**Mod Version**

seasonhud-1.16.5-1.4.20

**Modloader(Fabric/Forge/NeoForge)**

Forge

**Modloader Version**

Forge 36.2.39

**Additional Info (Crashlog/Modlist)**

[crash-2024-08-09_11.15.00-client.txt](https://github.com/user-attachments/files/16555634/crash-2024-08-09_11.15.00-client.txt)

**Comment by panda-lsy** [comment]
FTB Chunks Version:
ftb-chunks-forge-1605.3.4-build.220

**Comment by lanAnderson** [comment]
Give version 1.10.0 a shot, I backported all the recent changes I made to 1.16.5

**Comment by panda-lsy** [comment]
Thank you very much, it worked! But in the FTB chunks, the icon corresponding to the season turns into a white border character.
![image](https://github.com/user-attachments/assets/246b2707-e35d-414d-b394-45093fa38934)

**Comment by lanAnderson** [comment]
Which mod is providing the high res fonts? I use a custom font for the icon so it might be overriding it, but I can see if I can work around it

**Comment by panda-lsy** [comment]
ModernUI-1.16.5-2.7.1.105-universal
https://www.curseforge.com/minecraft/mc-mods/modern-ui
However, ModernUI for Minecraft 1.16.5 is no longer updated with support, I hope there's still a way to fix this

**Comment by panda-lsy** [comment]
I removed this mod from the modlist and it worked
![image](https://github.com/user-attachments/assets/cf8631cc-aadd-4e16-9a9a-0901abe7eaea)

**Comment by lanAnderson** [comment]
It looks like they added fixes in the 1.18.2. version.  I looked at the 1.16.5 version and couldn't find a way to override the font changes.
