### ISSUE TITLE
SeasonHUD crashes with newer FTB Chunks releases

### ISSUE THREAD

**Issue by ImAK9** [lanAnderson/SeasonInfo#105]
**Describe the issue**

- SeasonHUD crashes with newer FTB Chunks releases.
- Using build **2101.1.0** of FTB Chunks-

**Minecraft Version**

- 1.21.1

**Mod Version**

- 1.9.8

**Modloader(Fabric/Forge/NeoForge)**

- NeoForge

**Modloader Version**

- 21.1.23

**Additional Info (Crashlog/Modlist)**

- https://mclo.gs/N3EKAaf

**Comment by lanAnderson** [comment]
Should be fixed in 1.10.0
