### ISSUE TITLE
Unable to use this in 1.21.1

### ISSUE THREAD

**Issue by VaporeonScripts** [lanAnderson/SeasonInfo#108]
Describe the issue
cant use 1.21 with 1.21.1 minecraft

Minecraft Version

1.21.1

Mod Version

1.21-1.9.8

Modloader(Fabric/Forge/NeoForge)

fabric

Modloader Version

0.16.2 (latest)

Additional Info (Crashlog/Modlist)

.

**Comment by lanAnderson** [comment]
I'll take a look at this today.

**Comment by VaporeonScripts** [comment]
alright, ty

**Comment by lanAnderson** [comment]
Should be fixed in 1.10.0

**Comment by VaporeonScripts** [comment]
how can i make the hud appear?  as there is no way of opening the config ingame or any keybind for it

**Comment by VaporeonScripts** [comment]
even trying to make it go to the right with the config doesnt show it, i have serene seasons mod tho

**Comment by lanAnderson** [comment]
"H" is  default key to bring up the in game options (if you have Accessories installed, you may need to reassign it. They recently added a keybind for the same key). I tested on fresh install on 1.21.1 w/ Fabric and it appears to be working

**Comment by VaporeonScripts** [comment]
Yes,but I changed nothing and it's enabled,but I can't see it

**Comment by lanAnderson** [comment]
Can you upload you're "latest.log" and I'll see if I can replicate it.

**Comment by VaporeonScripts** [comment]
alright, lemme get it

**Comment by VaporeonScripts** [comment]
https://mclo.gs/ATv3RP7
