### ISSUE TITLE
New JourneyMap 1.21-6.0.0-beta.23 integration issue

### ISSUE THREAD

**Issue by mysticdrew** [lanAnderson/SeasonInfo#111]
JourneyMap dev here. 
I got a crash report. 
https://github.com/TeamJM/journeymap/issues/785

your failing code is here.
https://github.com/IanMods/SeasonHUD/blob/ce4d1de300d9c4fea257288249e014741fde3e53/common/src/main/java/club/iananderson/seasonhud/client/overlays/JourneyMapCommon.java#L60

I recently changed `getInfoLabelAreaHeight` to take a list instead of an array to support letting users move the info slots around. They are no longer static to top and bottom. You can set which ever ones you want to the top or bottom, include all 4 on top, or all 4 on bottom. 

New signature
`public int getInfoLabelAreaHeight(Font fontRenderer, Theme.LabelSpec labelSpec, List<ThemeLabelSource.InfoSlot> themeLabelSources)`

You can now change your code to this to get the variable heights, this is how I do it in journeymap.
Calling getInforSlotLabels returns a tuple, A is top labels, B is bottom labels, it is a public method.
```
        var tuple = getInfoSlotLabels(miniMapProperties);
        var topLabels = tuple.a();
        var bottomLabels = tuple.b();
        
        // Calculate areas reserved for info labels
        int topInfoLabelsHeight = getInfoLabelAreaHeight(fontRenderer, minimapSpec.labelTop, topLabels);
        int bottomInfoLabelsHeight = getInfoLabelAreaHeight(fontRenderer, minimapSpec.labelBottom, bottomLabels);
```

**Comment by mysticdrew** [comment]
Looks like we need to get what you need in our API so that changes do not break your mod.

**Comment by lanAnderson** [comment]
Thanks, should be fixed in version 1.10.3, that is currently uploading

**Comment by mysticdrew** [comment]
I am not familiar with your mod and what exactly you do with JM interaction. Are you just displaying a new text line above the top infoslot or below the bottom infoslot? 

If that is the case, I could look into adding an event to our API you can listen to, to display your custom infoslot. Also our API allows addons to add infoslots to the list, but it does not force display it. The user still needs to select it.

**Comment by lanAnderson** [comment]
Yeah basically just finding where the last info slot was drawn, and then using you're drawBatchLabel() method to draw and additional one above/below the others.  Basically how you draw them in the LabelVars class. 

I tried to use a custom infoslot originally , but it looks like it only accepts a string. I use a custom font for the season icon, and recolor the text based on  the season, so I would need it to accept a component.

**Comment by mysticdrew** [comment]
Ahh yea, I can do that.

**Comment by mysticdrew** [comment]
With beta.24 and the latest snapshot api, infoslot registration now supports Component, I did not get the event in yet, I had a crash I had get a fix out.

**Comment by mysticdrew** [comment]
![image](https://github.com/user-attachments/assets/c7c6371b-d4e1-408b-a11e-75be9e0e7779)
![image](https://github.com/user-attachments/assets/297bb4a1-70c4-4fdf-a74e-743b51dce319)

Will that work for you?  This will be in beta.25

**Comment by lanAnderson** [comment]
Awesome, I switched over to just using the InfoSlotRegistryEvent instead and it appears to be working, just need to test it a bit. 

I was also able to use new InfoSlotDisplayEvent to optionally add it to the top or bottom set instead, incase all the infoslots are in use already.

**Comment by mysticdrew** [comment]
> Awesome, I switched over to just using the InfoSlotRegistryEvent instead and it appears to be working, just need to test it a bit.
> 
> I was also able to use new InfoSlotDisplayEvent to optionally add it to the top or bottom set instead, incase all the infoslots are in use already.

That's great to hear! Glad to make things a bit simpler and less risk for breakage! Let me know if you need anymore hooks that do not exist in the API.
