### ISSUE TITLE
Ability to assign sub seasons to calendar only.

### ISSUE THREAD

**Issue by knighthawkUnlimited** [lanAnderson/SeasonInfo#113]
Hi. I was just wondering if you could possibly add the ability to attach only the sub season and day count to the calendar. So you will still know what season it is, but will gain extra detail when you have a calendar. Either way, thanks for the wondderful mod :)

**Comment by lanAnderson** [comment]
Added in v1.10.6

**Comment by knighthawkUnlimited** [comment]
Thank you! :)

**Comment by Foozey** [comment]
This was an amazing idea, thank you for implementing it Ian. Finally gives a use to the Calendar item without having to disable the default HUD entirely.
