### ISSUE TITLE
[1.19.2] Season Not in HUD

### ISSUE THREAD

**Issue by irish-brigid** [lanAnderson/SeasonInfo#117]
The current season is not displayed in the HUD. I have "Requires calendar" turned off and I have a calendar in a curios slot just in case. I'm also using GUI Compass, but I have the season set to appear in a different corner so it shouldn't affect this.

- .

Minecraft Version: 1.19.2

- .

Mod Version: 1.10.9

- .

Modloader: Forge 43.4.2

**Comment by lanAnderson** [comment]
I'm not able to replicate this. I loaded a fresh instance with the following:

1. SeasonHUD
2. SereneSeasons
3. Curios
4. GUI Compass (just in case)

and everything was displaying correctly with the same settings.

**Comment by irish-brigid** [comment]
Okay, but I still don't see the HUD.
