### ISSUE TITLE
Day count wrong with mods like time & wind

### ISSUE THREAD

**Issue by xR4YM0ND** [lanAnderson/SeasonInfo#119]
So in the Aged Modpack i set the day to 24000 & the night to 12000 ticks
Which is overhaul 36000 ticks per whole day

& A season should have 16 days but the seasonshud day counter says 24

Would be awesome to define a whole day in ticks in the config instead of 24000 t vanilla

**Comment by lanAnderson** [comment]
Added in v1.11.1
