### ISSUE TITLE
Resurgence of FTB Chunks Crashing?

### ISSUE THREAD

**Issue by ItzLyfe** [lanAnderson/SeasonInfo#122]
**Describe the issue**
- I might be a dumbass, but seems FTB Chunks issue has reappeared?

**Minecraft Version**
- 1.20.1

**Mod Version**
- 1.20.1-1.11.2 (HUD)/1.20.1-9.3.0.27 & 1.20.1-9.1.0.0

**Modloader(Fabric/Forge/NeoForge)**
- Forge

**Modloader Version**
- 47.3.1

**Additional Info (Crashlog/Modlist)**
- [Crashlogs]
[9.1.0.0.txt](https://github.com/user-attachments/files/17609463/9.1.0.0.txt)
[9.3.0.27.txt](https://github.com/user-attachments/files/17609464/9.3.0.27.txt)

**Comment by lanAnderson** [comment]
Looks like they backported the 1.21 changes. Fixed in 1.11.3
