### ISSUE TITLE
Server-sided curio slot

### ISSUE THREAD

**Issue by eligibbs** [lanAnderson/SeasonInfo#124]
As the mod is client-side only, the curio slot is missing for servers. Is there a way to make it non-sided, a datapack for this, or some other solution?

**Comment by lanAnderson** [comment]
You should be able to include it on the server to get the curio slot. I tested it on my 1.20.1 server to make sure.

If you use something like ModOptimizer to automatically disable client side mods, add this line to the config:

`seasonhud = "server"`
 
Let me know if that isn't the case.

**Comment by eligibbs** [comment]
I apologize! I must have seen it crash my server and figured, "since it's client-side it's not needed server-side, I'll remove so I can avoid the crash." Here's a
[crashlog](https://github.com/user-attachments/files/18268374/crash-2024-12-28_22.46.14-fml.txt) with the current build of my server

**Comment by eligibbs** [comment]
I should also mention crash only happens server side with this pack, and on several versions of forge for 1.20.1. I'll just make an issue for it as that seems more pertinent as it isn't just my pack, and deals with FTB Chunks directly
