### ISSUE TITLE
Crash on Server-Side for 1.20.1

### ISSUE THREAD

**Issue by eligibbs** [lanAnderson/SeasonInfo#125]
**Describe the issue**
Server crashes when this and its dependents are installed with FTB family of mods as mentioned in #124 
- .

**Minecraft Version**
1.20.1 forge
- .

**Mod Version**
1.11.6 and 1.11.4 at minimum
- .

**Modloader(Fabric/Forge/NeoForge)**
Forge
- .

**Modloader Version**
47.3.12 and 47.3.22
- .

**Additional Info (Crashlog/Modlist)**
[Log](https://github.com/user-attachments/files/18268463/latest.log), [modlist](https://github.com/user-attachments/assets/d61a4ad6-4099-427b-b60e-52355d8fbd98), and [crashlog](https://github.com/user-attachments/files/18268461/crash-2024-12-28_23.28.29-fml.txt)

- .

**Comment by lanAnderson** [comment]
Should be fixed in 1.11.7
