### ISSUE TITLE
Incorrect displayed day

### ISSUE THREAD

**Issue by zanadoman** [lanAnderson/SeasonInfo#28]
![image](https://github.com/lanAnderson/SeasonHUD/assets/88244790/bd88146b-e535-4249-be6d-67c1cd6a9227)
Mods: Serene seasons, SeasonHUD and Serene seasons fix + journey map for display
The displayed day was incorrect even before the seasons fix mod.

**Comment by lanAnderson** [comment]
I'll take a look when I get home later today. Which game version was this example on?

**Comment by zanadoman** [comment]
Hi, version is forge 1.19.2 - 43.2.9
Good news I found the specific issue
![image](https://github.com/lanAnderson/SeasonHUD/assets/88244790/53ef0371-1636-4a15-ab5d-ed48196f57dc)
On this server the subseason length is set to 30day instead of 8 (default). I resetted the season to day 1 and the hud worked correctly until day 8 because the next day was day 1 instead of 9.

**Comment by lanAnderson** [comment]
Thank you!

I'll see if I can access the custom subseason lengths, and work that into the math.

**Comment by zanadoman** [comment]
My thanks mate!

**Comment by lanAnderson** [comment]
e5049fe

Fixed in 1.4.16

**Comment by zanadoman** [comment]
Working properly thank you in the name of the server!
