### ISSUE TITLE
[1.20.1] Crash with FTB Chunks

### ISSUE THREAD

**Issue by HockeyZman2000** [lanAnderson/SeasonInfo#35]
[crash-2023-07-11_21.59.32-client.txt](https://github.com/lanAnderson/SeasonHUD/files/12023300/crash-2023-07-11_21.59.32-client.txt)

Not sure what is happening here tbh

**Comment by lanAnderson** [comment]
Should be fixed in version 1.4.20 that is uploading now

**Comment by HockeyZman2000** [comment]
Thanks mate!
