### ISSUE TITLE
UI rendering error in text of season

### ISSUE THREAD

**Issue by CAlldredgeDev** [lanAnderson/SeasonInfo#38]
In the ui for all the seasons, except Fall, it works and looks great. When Fall rolls around it turns the season text display into desc.seasonhud.fall. There is no other issue just the ingame text reads odd.

**Comment by lanAnderson** [comment]
Should be fixed in 1.5.4 that is currently uploading. I forgot FabricSeasons calls it Fall, and not Autumn, like SereneSeason's does.
