### ISSUE TITLE
Breaks trinkets:hand/ring tag due to incorrect namespace

### ISSUE THREAD

**Issue by muon-rw** [lanAnderson/SeasonInfo#43]
https://github.com/lanAnderson/SeasonHUD/blob/86347112266fe829c5da516631622640c26017ba/fabric/src/main/resources/data/trinkets/tags/items/hand/ring.json

The ID is listed in your tag as seasons:season_calendar, but the calendar is part of fabric seasons extras, so the ID is seasonsextras:season_calendar, at least on 1.20+ - not sure about older versions. 

The incorrect ID causes no items to be equippable in the mainhand ring slot at all, unless overriding the tag with a datapack or using a mod like LMFT.

**Comment by lanAnderson** [comment]
Thanks, forgot to change that one. Should be fixed in the next release
