### ISSUE TITLE
Season icon won't shift alongside with the text under Xaero's Minimap

### ISSUE THREAD

**Issue by ChromaPIE** [lanAnderson/SeasonInfo#45]
![image](https://github.com/lanAnderson/SeasonHUD/assets/56111366/6744bb02-27ce-43be-8666-9588802ca0be)

![image](https://github.com/lanAnderson/SeasonHUD/assets/56111366/8ddfc4ad-0678-4cf7-ad1a-65c67aeef9cf)

Notice that the Spring icon stays where it was even when all other elements' position got shifted bc of the status effect above the minimap.

**Comment by 909oce** [comment]
i have this too, its been bugging me for days, wish i could even just disable the icon

**Comment by 909oce** [comment]
however i dont have a status effect, so its just permanently bugged out in the wrong spot, so idk

**Comment by 909oce** [comment]
![image](https://github.com/lanAnderson/SeasonHUD/assets/21692038/1b5173c2-074f-45a0-9d88-9afc94403944)

**Comment by lanAnderson** [comment]
Version 1.5.9 will have fix it for the majority of minimap positions when potion effects are displayed. It will likely be out tomorrow, as I need to test the versions other than 1.20.1 to make sure I didn't break anything.

@909oce : I'm not able to replicate that problem. Open up a new issue, and include the Minecraft/mod version. If you include the "xaerominimap.txt" config file, that may help me replicate it as well.
