### ISSUE TITLE
JourneyMap: Text rendering behind background

### ISSUE THREAD

**Issue by AngellusMortis** [lanAnderson/SeasonInfo#46]
Using the mod for JourneyMap causes the text to render behind the background.

Default (80%) Info Slot Background Opacity:
![image](https://github.com/lanAnderson/SeasonHUD/assets/490848/14f19c13-ce07-48bb-8c3e-fc1eb0ad5342)

100% Info Slot Background Opacity:
![image](https://github.com/lanAnderson/SeasonHUD/assets/490848/6999756e-fb38-4929-8c9b-06a57461464e)

Should be using the latest 1.20.1 versions of both:
Journeymap: 5.9.15
SeasonHUB: 1.5.9

**Comment by lanAnderson** [comment]
Should be fixed in 1.5.10, which is currently uploading
