### ISSUE TITLE
How do I change the opacity of the background behind the text?

### ISSUE THREAD

**Issue by Ricenami** [lanAnderson/SeasonInfo#47]
Hi, I love your mod, is there any way I can change the opacity of the background for the text so that its transparent? Right now, its this bluish-greenish color, and the rest of the text such as the coordinates and biome don't have a background.

If not, could we get datapack support to change the color/background opacity?

Cheers!

**Comment by lanAnderson** [comment]
Let me take a look over the next few days. 

I assume your are using Journeymap, since I think that's the only one with background color. It should be pulling the color info automatically, but there have been a few changes to Journeymap that I might need to look into.

**Comment by Ricenami** [comment]
Yes that's correct! And okay, keep me updated. :)

![image](https://github.com/lanAnderson/SeasonHUD/assets/107516246/95c19f1d-e74e-4a23-996b-dc451c6602e2)

**Comment by lanAnderson** [comment]
Can you list the following for me? I did a quick test and it seemed to be working correctly for me, but I only checked a couple versions:

  - Mod Version
  - JourneyMap Version
  - Minecraft Version
  - Forge/Fabric Version

**Comment by Ricenami** [comment]
For sure! Also just to clarify I don't know where to change the opacity for the background text.

- seasonhud 1.5.6
- journeymap 5.9.7
- minecraft 1.19.2
- fabric 14.22

**Comment by lanAnderson** [comment]
Should be fixed now in version 1.5.11

**Comment by Ricenami** [comment]
Thank you!!
