### ISSUE TITLE
Season Icon out of alignment for Xaero's Minimap/Worldmap

### ISSUE THREAD

**Issue by Gantros** [lanAnderson/SeasonInfo#49]
SeasonHUD v1.5.12
Xaero's Minimap v23.6.4
Xaero's World Map v 1.36.0

The Season info under the minimap is out of alignment. This doesn't appear to happen when first entering the world, but it appears to be triggered by going in and out of the Xaero GUI. 
![2023-10-23_13 26 53](https://github.com/lanAnderson/SeasonHUD/assets/63207219/c3b0bfe0-eced-4b68-a84e-1c4c52706113)

**Comment by lanAnderson** [comment]
Hmm I tried to replicate this for a bit but wasn't able to. Which Minecraft version / Modloader are you on?

Also, are you using a modpack or have a modlist you can share? I can see if there is an incompatibility I need to fix

**Comment by Gantros** [comment]
MC v1.20.1
MultiMC Modloader
Forge v47.2.1

Mods:
  [✔️] (1.20.1)+grapple-1.0.1.jar
  [✔️] AdditionalPlacements-1.20-1.7.5.jar
  [✔️] AdLods-1.20.1-8.1.0.0-build.0142.jar
  [✔️] AI-Improvements-1.20-0.5.2.jar
  [✔️] AirHop-v8.0.0-1.20.1-Forge.jar
  [✔️] alexscaves-1.0.5.jar
  [✔️] alexsmobs-1.22.5.jar
  [✔️] almostunified-forge-1.20.1-0.7.0.jar
  [✔️] animal_feeding_trough-1.0.3+1.20.1-forge.jar
  [✔️] appleskin-forge-mc1.20.1-2.5.0.jar
  [✔️] architectury-9.1.11-forge.jar
  [✔️] armorstandshiftswap-1.20.1-0.0.1.jar
  [✔️] astikorcarts-1.20.x-1.1.6.jar
  [✔️] athena-forge-1.20.1-3.1.1.jar
  [✔️] balm-forge-1.20.1-7.1.4.jar
  [✔️] BetterBeekeeping-1.20.1-1.3.0.jar
  [✔️] bettercombat-forge-1.7.4+1.20.1.jar
  [✔️] betterdays-1.20.1-3.1.0.3-FORGE.jar
  [✔️] better-respawn-forge-1.20.1-2.0.3.jar
  [✔️] betterspawnercontrol-1.20.1-4.2.jar
  [✔️] bettervillage-forge-1.20.1-3.2.0.jar
  [✔️] bigbrain-1.20-1.7.3.jar
  [✔️] Bookshelf-Forge-1.20.1-20.1.6.jar
  [✔️] brazier-forge-6.1.1.jar
  [✔️] buildersaddition-1.20.1-20230928a.jar
  [✔️] BuildGuide-1.20-0.3.3.jar
  [✔️] Butchersdelight+beta+1.20.1+2.0.8f.jar
  [✔️] carryon-forge-1.20.1-2.1.2.5.jar
  [✔️] chalk-1.20.1-1.6.2.jar
  [✔️] charmofundying-forge-6.4.4+1.20.1.jar
  [✔️] chickensshed-1.4.0-0.jar
  [✔️] chipped-forge-1.20.1-3.0.1.jar
  [✔️] citadel-2.4.7-1.20.1.jar
  [✔️] cloth-config-11.1.106-forge.jar
  [✔️] Clumps-forge-1.20.1-12.0.0.3.jar
  [✔️] collective-1.20.1-6.66.jar
  [✔️] comforts-forge-6.3.4+1.20.1.jar
  [✔️] corpse-1.20.1-1.0.3.jar
  [✔️] create_enchantment_industry-1.20.1-for-create-0.5.1.e-1.2.7.f.jar
  [✔️] create_jetpack-forge-4.1.1.jar
  [✔️] create_mechanical_extruder-1.20.1-1.5.7.e-22.jar
  [✔️] create_recycle_1.0.2_forge_1.20.1.jar
  [✔️] create-1.20.1-0.5.1.e.jar
  [✔️] creategoggles-1.20.1-0.5.5.e_hf-[FORGE].jar
  [✔️] CreativeCore_FORGE_v2.11.5_mc1.20.1.jar
  [✔️] cristellib-1.1.3-forge.jar
  [✔️] cryingportals-1.20.1-2.3.jar
  [✔️] cupboard-1.20.1-2.1.jar
  [✔️] curios-forge-5.4.0+1.20.1.jar
  [✔️] dismountentity-1.20.1-3.0.jar
  [✔️] DistractingTrims-Forge-1.20.1-2.0.3.jar
  [✔️] domesticationinnovation-1.7.0-1.20.jar
  [✔️] doubledoors-1.20.1-5.0.jar
  [✔️] DramaticDoors-QuiFabrge-1.20.1-3.1.0_1.jar
  [✔️] EasyAnvils-v8.0.1-1.20.1-Forge.jar
  [✔️] embeddium-0.2.2+mc1.20.1.jar
  [✔️] EnchantmentDescriptions-Forge-1.20.1-17.0.8.jar
  [✔️] enchantmenttransfer-0.0.6-1.20.1.jar
  [✔️] entityculling-forge-1.6.2-mc1.20.jar
  [✔️] ExplorersCompass-1.20.1-1.3.3-forge.jar
  [✔️] FarmersDelight-1.20.1-1.2.3.jar
  [✔️] FastFurnace-1.20.1-8.0.1.jar
  [✔️] FastSuite-1.20.1-5.0.1.jar
  [✔️] FastWorkbench-1.20.1-8.0.2.jar
  [✔️] ferritecore-6.0.1-forge.jar
  [✔️] ForgeEndertech-1.20.1-11.1.0.0-build.0142.jar
  [✔️] FramedBlocks-9.1.6.jar
  [✔️] geckolib-forge-1.20.1-4.2.3.jar
  [✔️] Grass_Overhaul-Forge-23.10.10-MC1.20.1.jar
  [✔️] hole_filler_mod-1.2.8_mc-1.20_forge.jar
  [✔️] Homeostatic-1.20.1-2.9.4.7.jar
  [✔️] Incendium_1.20.2_v5.3.2.jar
  [✔️] InventoryProfilesNext-forge-1.20-1.10.6.jar
  [✔️] Jade-1.20.1-forge-11.6.3.jar
  [✔️] JadeAddons-1.20.1-forge-5.2.0.jar
  [✔️] jei-1.20.1-forge-15.2.0.27.jar
  [✔️] justenoughbreeding-forge-1.20.x-1.0.9.jar
  [✔️] Kiwi-1.20.1-forge-11.1.1.jar
  [✔️] kotlinforforge-4.5.0-all.jar
  [✔️] LeavesBeGone-v8.0.0-1.20.1-Forge.jar
  [✔️] libIPN-forge-1.20-3.0.2.jar
  [✔️] libraryferret-forge-1.20.1-4.0.0.jar
  [✔️] mcw-bridges-2.1.1-mc1.20.1forge.jar
  [✔️] mcw-doors-1.1.0forge-mc1.20.1.jar
  [✔️] mcw-fences-1.0.7-mc1.20.1forge.jar
  [✔️] mcw-furniture-3.2.0-mc1.20.1forge.jar
  [✔️] mcw-lights-1.0.6-mc1.20.1forge.jar
  [✔️] mcw-paths-1.0.3forge-mc1.20.1.jar
  [✔️] mcw-roofs-2.2.4b-mc1.20.1forge.jar
  [✔️] mcw-trapdoors-1.1.1-mc1.20.1forge.jar
  [✔️] memorysettings-1.20.1-5.4.jar
  [✔️] merenc-forge-1.20.x-v3.2.jar
  [✔️] modernfix-forge-5.8.1+mc1.20.1.jar
  [✔️] moonlight-1.20-2.8.51-forge.jar
  [✔️] moveboats-1.20.1-3.0.jar
  [✔️] NaturesCompass-1.20.1-1.11.2-forge.jar
  [✔️] netherportalfix-forge-1.20-13.0.0.jar
  [✔️] Nullscape_1.20.2_v1.2.3.jar
  [✔️] nutritiousmilk-1.20.1-3.1.jar
  [✔️] obsidianui-0.1.2+1.20.1.jar
  [✔️] Patchouli-1.20.1-81-FORGE.jar
  [✔️] placeableblazerods-1.20.1-3.1.jar
  [✔️] Placebo-1.20.1-8.3.7.jar
  [✔️] player-animation-lib-forge-1.0.2-rc1+1.20.jar
  [✔️] polymorph-forge-0.49.1+1.20.1.jar
  [✔️] prettybeaches-forge-1.20-11.0.1.jar
  [✔️] PuzzlesLib-v8.0.24-1.20.1-Forge.jar
  [✔️] radiantgear-forge-2.1.1+1.20.1.jar
  [✔️] realisticbees-1.20.1-3.4.jar
  [✔️] recipeessentials-1.20.1-2.9.jar
  [✔️] redstonepen-1.20.1-neoforge-1.3.21.jar
  [✔️] reefredux-1.20.1-1.1.1.jar
  [✔️] resourcefullib-forge-1.20.1-2.1.11.jar
  [✔️] Ryoamiclights-0.1.4+1.20.1.jar
  [✔️] saturn-mc1.20.1-0.0.7.jar
  [✔️] scaffoldingdropsnearby-1.20.1-3.0.jar
  [✔️] seasonhud-forge-1.20.1-1.5.12.jar
  [✔️] SereneSeasons-1.20.1-9.0.0.46.jar
  [✔️] sliceanddice-forge-3.2.0.jar
  [✔️] smoothchunk-1.20.1-3.3.jar
  [✔️] SoLOnion_FORGE_v1.1.3_mc1.20.1.jar
  [✔️] sophisticatedbackpacks-1.20.1-3.18.65.935.jar
  [✔️] sophisticatedcore-1.20.1-0.5.100.457.jar
  [✔️] spyglass_improvements-1.4+mc1.20+forge.jar
  [✔️] Steam_Rails-1.5.2+forge-mc1.20.1.jar
  [✔️] storagedrawers-1.20.1-12.0.2.jar
  [✔️] supplementaries-1.20-2.6.16.jar
  [✔️] TaxFreeLevels-1.3.6-forge-1.20.2.jar
  [✔️] TerraBlender-forge-1.20.1-3.0.0.169.jar
  [✔️] Terralith_1.20.2_v2.4.7(modified).jar
  [✔️] textrues_embeddium_options-0.1.2+mc1.20.1.jar
  [✔️] togenc-forge-1.20.x-v1.0.jar
  [✔️] trashslot-forge-1.20-15.0.0.jar
  [✔️] trowels-1.20-2.0.0.jar
  [✔️] village_nullifier-2.0.0.jar
  [✔️] village-nullifier-terralith-2.0.0.jar
  [✔️] weakerspiderwebs-1.20.1-3.2.jar
  [✔️] world_preview-forge-1.20-1.1.0.jar
  [✔️] WWOO-FABRIC+FORGE+QUILT-2.0.0.jar
  [✔️] Xaeros_Minimap_23.8.4_Forge_1.20.jar
  [✔️] XaerosWorldMap_1.36.0_Forge_1.20.jar
  [✔️] YungsApi-1.20-Forge-4.0.2.jar
  [✔️] YungsBetterDesertTemples-1.20-Forge-3.0.3.jar
  [✔️] YungsBetterDungeons-1.20-Forge-4.0.3.jar
  [✔️] YungsBetterJungleTemples-1.20-Forge-2.0.4.jar
  [✔️] YungsBetterMineshafts-1.20-Forge-4.0.4.jar
  [✔️] YungsBetterNetherFortresses-1.20-Forge-2.0.5.jar
  [✔️] YungsBetterOceanMonuments-1.20-Forge-3.0.3.jar
  [✔️] YungsBetterStrongholds-1.20-Forge-4.0.3.jar
  [✔️] YungsBetterWitchHuts-1.20-Forge-3.0.3.jar

**Comment by lanAnderson** [comment]
Thank you! I'll take a look at this when I get home from work. 

Just in case, can you also upload your Xaero's Minimap config file? That will make it easier to see if there is an option you have on that I'm not accounting for.

**Comment by Gantros** [comment]
[xaerominimap.txt](https://github.com/lanAnderson/SeasonHUD/files/13127093/xaerominimap.txt)
[xaerominimap_entities.json](https://github.com/lanAnderson/SeasonHUD/files/13127094/xaerominimap_entities.json)
[xaerominimap-common.txt](https://github.com/lanAnderson/SeasonHUD/files/13127095/xaerominimap-common.txt)
[xaeroworldmap.txt](https://github.com/lanAnderson/SeasonHUD/files/13127096/xaeroworldmap.txt)
[xaeroworldmap-common.txt](https://github.com/lanAnderson/SeasonHUD/files/13127097/xaeroworldmap-common.txt)

**Comment by lanAnderson** [comment]
Hmm, I tried your config with the exact versions and tested with the majority of those mods, but I still can't get it to replicate. You said going into the Xaero menu seems to cause it to happen. Is that the full screen map (default M key) or the minimap options (default Y key)?

Also, if you have the chance, can you load a profile with just SeasonHUD, SereneSeasons, and the Xaero Mods, and see if the same thing still happens. That will help me narrow down if it's another mod causing it, or maybe certain display settings.

**Comment by Gantros** [comment]
Honestly I just assumed it was xaero’s because that’s what I recalled doing before I noticed the problem. It seems to fix itself when reloading, and I haven’t seen the issue recently. I’ll try to keep a mental note to track what I was doing for replication.

**Comment by Gantros** [comment]
I may have a clue to the problem: The HUD was fine until I completed an eating cycle, then the icon under the minimap shifted.

**Comment by lanAnderson** [comment]
Got it, I was able to replicate that. The icon moves down when there is a potion effect, as the minimap usually does, but the effects from Spice of Life Onion are hidden. 

Let me see how the are handling things and try to work around that.

**Comment by lanAnderson** [comment]
SHOULD be fixed in 1.5.13, that is currently uploading.
