### ISSUE TITLE
Unnecessary Injection Attempt

### ISSUE THREAD

**Issue by Sweek9** [lanAnderson/SeasonInfo#50]
I noticed that the mod attempts to access and inject to Xaero's Minimap when that mod is not installed, throwing warnings:
```
[main/WARN] [mixin/]: Error loading class: xaero/common/minimap/info/BuiltInInfoDisplays (java.lang.ClassNotFoundException: xaero.common.minimap.info.BuiltInInfoDisplays)
[main/WARN] [mixin/]: @Mixin target xaero.common.minimap.info.BuiltInInfoDisplays was not found seasonhud.mixins.json:XaeroBuiltInInfoDisplays
```
For efficiency / faster mod loading you could embed that portion of the code in an if-statement to check if Xaero's Minimap is present before it's run. My MineCraft modding knowledge is limited, but if I recall correctly you can do the check using: 
```
if(ModList.get().isLoaded("xaerominimap"))
{// Code For Xaero's Minimap:
}
```

**Comment by lanAnderson** [comment]
I researched Mixins a bit more, and found the issue. Should be fixed in the next release
