### ISSUE TITLE
Season Icon possible Incompat with Open Parties and Claims

### ISSUE THREAD

**Issue by GamerTable** [lanAnderson/SeasonInfo#51]
While on a Claimed chunk the Season text moves with the Info but the Icon doesn't 
1.19.2 SeasonHUD 1.5.13

While on Forceloaded Chunk: 
![2023-11-10_20 06 51](https://github.com/lanAnderson/SeasonHUD/assets/114619268/98e6c29f-8233-4b70-be05-eadd6cad9744)

While on Claimed Chunk 
![2023-11-10_20 06 45](https://github.com/lanAnderson/SeasonHUD/assets/114619268/ff92b5ca-7bb4-40ae-a9e7-78fc940c68b0)

Outside of Claims 
![2023-11-10_20 11 38](https://github.com/lanAnderson/SeasonHUD/assets/114619268/7f74a887-2d30-4b62-82db-910cfd84f56c)

Configs: 
[xaerominimap.txt](https://github.com/lanAnderson/SeasonHUD/files/13324019/xaerominimap.txt)
[xaeroworldmap.txt](https://github.com/lanAnderson/SeasonHUD/files/13324021/xaeroworldmap.txt)
SeasonHUD is on Defaults

**Comment by lanAnderson** [comment]
Thanks, I didn't account for the claim info overflowing to two lines if the text long enough.  Let me take a look and see if I can fix it for the next release

**Comment by GamerTable** [comment]
Cool, btw
Another thing I noticed is when you use the Xaero Minimap key to expand the minimap the icon also stays in place and overlaps with the map
I'll send a screenshot later

**Comment by GamerTable** [comment]
Whoops

**Comment by lanAnderson** [comment]
Both of these should be fixed in next release. It should be out in a day or two, I just need to port it to the rest of the versions and test .
