### ISSUE TITLE
[1.20.1 Forge] Misalginment w/MapAtlases due to new update.

### ISSUE THREAD

**Issue by PlayfulPiano** [lanAnderson/SeasonInfo#52]
![image](https://github.com/lanAnderson/SeasonHUD/assets/3158887/6404db68-1d11-4243-a58c-4b41307a5e9c)
Heads up but now there's a chunk coordinate line with mapatlases in the latest, so it causes a misalignment with seasonhud.

**Comment by lanAnderson** [comment]
Thanks, fixed in v1.6.2 which should be uploaded now
