### ISSUE TITLE
Icon and text overlap - Modern UI

### ISSUE THREAD

**Issue by QianFuv** [lanAnderson/SeasonInfo#53]
when font behavior change to Keep ASCII
![image](https://github.com/lanAnderson/SeasonHUD/assets/111696321/ca5f0f30-e8ce-45b4-86aa-88de589991b7)
![image](https://github.com/lanAnderson/SeasonHUD/assets/111696321/b13571f2-41c6-4f4b-a5dc-11886753cb73)
when font behavior change to Keep other
![image](https://github.com/lanAnderson/SeasonHUD/assets/111696321/a7ded790-4932-4a16-99ea-5ae89717e062)
![image](https://github.com/lanAnderson/SeasonHUD/assets/111696321/ebe22fa7-7cdd-4111-bdd0-e26a2ac2e005)

**Comment by lanAnderson** [comment]
Should be working in the 1.7.0 update I'm finishing up. I redid how the icons are drawn and tested it with ModernUI.

**Comment by QianFuv** [comment]
Good job! The additional question is whether the compatibility of other language is verified?

**Comment by QianFuv** [comment]
For ease of understanding I use English presentation, but my native language is Chinese.
