### ISSUE TITLE
Season icon doesn't move with text - Xaero's Minimap

### ISSUE THREAD

**Issue by steve-the-player** [lanAnderson/SeasonInfo#55]
![2023-12-17_13 46 25](https://github.com/lanAnderson/SeasonHUD/assets/61434698/0298c195-079f-4ae8-ae15-8d9e6e6e77b6)
the map and current season text move down when there's an effect active, but the season icon does not

**Comment by lanAnderson** [comment]
Shouldn't happen anymore in v1.7.0, which should be out soon
