### ISSUE TITLE
Crash on latest version 1.7.0
[Fabric 0.14.24/1.20.1]

### ISSUE THREAD

**Issue by FallenNoober** [lanAnderson/SeasonInfo#57]
![crash-2023-12-21_11.21.44-client.txt](https://github.com/lanAnderson/SeasonHUD/files/13734957/crash-2023-12-21_11.21.44-client.txt)

crashed at start 
fine when removed  the seasonhud 
using ftbchunks as maptool
tried remove the mod that mentioned in crashtext , would error with another mod at 'main'

sorry for edited alot , something wrong with my edge XD

**Comment by lanAnderson** [comment]
Should be fixed in v1.7.1, which just uploaded
