### ISSUE TITLE
[Fabric 0.14.24/1.20.1/1.7.1] Crash with FTB Chunks 

### ISSUE THREAD

**Issue by FallenNoober** [lanAnderson/SeasonInfo#58]
kinds like #issue54 , but not sure
crash when loading the map
problem don't always arise
into the world by chance
![crash-2023-12-22_14.02.08-client.txt](https://github.com/lanAnderson/SeasonHUD/files/13749006/crash-2023-12-22_14.02.08-client.txt)

add：single world is fine，but multiplay world still crash

**Comment by lanAnderson** [comment]
Should be fixed in 1.7.2
