### ISSUE TITLE
[Fabric 0.14.24/1.20.1/1.7.1] Abnormal Default HUD Position and Scale

### ISSUE THREAD

**Issue by kurisubrooks** [lanAnderson/SeasonInfo#59]
I'm not sure if this is a bug specifically since there are options in the config file to be able to manually change the X/Y offset, but it's my assumption that perhaps this isn't the intended *default* behaviour, so I'll be reporting this as a bug.

Upon installing the mod and using it for the first time with the BigChadGuys Plus 1.1.6 modpack, the location of the SeasonHUD is both abnormally small and in a very strange spot (top-middle of screen). Screenshot below:

![image](https://github.com/lanAnderson/SeasonHUD/assets/6291467/69310c95-0480-47b9-b664-0a90b6b009e9)

Applicable versions and mods:
- Fabric 0.14.24
- Minecraft 1.20.1
- JourneyMap 5.9.18
- FTBChunks 2001.2.4
- SeasonHUD Fabric 1.7.1

System information:
- OS: macOS Sonoma 14.0
- CPU: Apple M1 Pro
- Java 17 (Zulu JDK)

Client Log: https://mclo.gs/kcgS8n9

**Comment by lanAnderson** [comment]
The scale is likely correct, the 1x scale on Journeymap is shockingly small. I couldn't replicate the position issue on Windows though, and don't have a Mac to test on.

I rewrote most of the Journeymap code, to try and fix it. I uploaded a preview version here if you can test it out and see if it's any better:

[1.7.2](https://github.com/lanAnderson/SeasonHUD/releases/tag/1.7.2)

**Comment by kurisubrooks** [comment]
Using this new pre-release version, unfortunately the issue appears to be unchanged. Your comments however did give me a thought though, which I have now confirmed.

This appears to be related to macOS HiDPI scaling. Macs generally use very high resolution + high pixel density "Retina" displays, so the default scale according to the OS is higher than the 1x of a standard 1080p Windows device counterpart.

Iris has this setting which lets me half the resolution of the game to get around this, which let me easily test this below.
<img width="1192" alt="image" src="https://github.com/lanAnderson/SeasonHUD/assets/6291467/ef1a60aa-2989-4542-9f89-ea0d496d6cda">

(macOS - 2x scaling - default)
![image](https://github.com/lanAnderson/SeasonHUD/assets/6291467/0589b0e3-adc2-4f4d-8ef7-0c5aa74b0afc)
(macOS - 1x scaling? "halved resolution")
![image](https://github.com/lanAnderson/SeasonHUD/assets/6291467/4c48781b-077c-43f2-b810-e72fa170827c)

Might be a change as simple as checking for the display resolution scale and then halving the scale/coords? Not sure how this would be handled in Java, especially with Minecraft. Sorry that I can't help further but hopefully this has been helpful.

**Comment by lanAnderson** [comment]
I made some more may have fixed it, and it is the version 1.7.2  just uploaded to Curseforge/Modrinth.  If not, there is a function to detect if someone is using OSX, so I could take a look and see what I need to half to correct the scaling, and create a toggle.

**Comment by kurisubrooks** [comment]
No change in 1.7.2-fabric from Modrinth.

![image](https://github.com/lanAnderson/SeasonHUD/assets/6291467/65c37f6f-efac-410b-bf99-0c3c113e8e39)

Here's the log: https://mclo.gs/Zfhma1z

**Comment by kurisubrooks** [comment]
Just took a look at the source code for the update and saw that you're using JourneyMap's info slots now, and upon testing this does indeed work - though without the icon/glyph. Is there a way to disable the old implementation when using it as an info slot?

![image](https://github.com/lanAnderson/SeasonHUD/assets/6291467/7bc04476-7aa6-4b12-8a51-550a2e05eeaa)

**Comment by lanAnderson** [comment]
Yeah I was planning on making that a toggleable option, since there is a limited number of slots showable, but I haven't been able to get it to display the custom font for the icons yet.

I added a quick option in the settings menu (default H key) / config to change the math to be 1/2 the screen resolution. I think that is correct, since the opposite made it look similar to yours when I tried it.

[1.7.2 MacOS Test](https://github.com/lanAnderson/SeasonHUD/releases/tag/1.7.2)

**Comment by kurisubrooks** [comment]
I can confirm that this version works upon toggling "MacOS Retina Display" under the settings menu 👍🏻 

![image](https://github.com/lanAnderson/SeasonHUD/assets/6291467/b7e4f234-b1cd-4738-89aa-61e026d311c7)

(Small suggestion: for the settings menu, macOS is officially capitalised as such, without the capital M at the start)

**Comment by lanAnderson** [comment]
Awesome, I'll clean it up a bit and release a proper update tomorrow. I corrected the capitalization in them menu and config file
