### ISSUE TITLE
"Show when minimap is hidden" does not seem to work with Map Atlases mod

### ISSUE THREAD

**Issue by MCRusher** [lanAnderson/SeasonInfo#61]
The option "Show when minimap is hidden"  appears to do nothing and you cannot see the season info if you don't have a map atlas equipped regardless of what it is set to.

This behavior is present in the Fabric 1.20.1-1.7.5 version of the SeasonHud mod 

---

As a side note, thanks for making and maintaining this mod, not only is season info nice to have on the hud but the day counter is also really nice since it lets me know how long I've been surviving in that world.

**Comment by lanAnderson** [comment]
Thanks, I found the issue and it should be fixed in v1.7.6
