### ISSUE TITLE
[Mod Support Request] GUI Clock by Serilium

### ISSUE THREAD

**Issue by ghost** [lanAnderson/SeasonInfo#62]
Sorry for posting in issues, but it would be cool if you added support for Serilium's GUI Clock 😎👍

**Comment by lanAnderson** [comment]
Something like the ingame time showing under the season line? I can add that and make a config option for that, unless their is something specific with the GUI Clock mod

**Comment by ghost** [comment]
GUI clock makes it so you can ONLY see time if you have a clock in your inventory, possibly you could make it only show seasons when holding a clock or if Fabric Seasons: Extras is installed a calendar.

![image](https://github.com/lanAnderson/SeasonHUD/assets/154561005/5d630453-6a31-48e3-bdbb-583fcfbcd4ee)
