### ISSUE TITLE
GUI Scaling Issue with MapAtlases

### ISSUE THREAD

**Issue by onycius** [lanAnderson/SeasonInfo#64]
Hello, 

The 1.20.1-1.7.7 Forge version of SeasonHUD seems to be incompatible with minimap scaling within MapAtlases. Changing the scale of the minimap to be greater than 1 will cause the entire Minecraft HUD+window to zoom in when holding an atlas in hand. This does not happen with SeasonHUD removed. Attached is a screenshot of SeasonHUD with MapAtlas:

![image](https://github.com/lanAnderson/SeasonHUD/assets/25759827/cbf0f209-a4c0-4caa-a822-d49212e27618)

**Comment by lanAnderson** [comment]
Should be fixed in version 1.7.8
