### ISSUE TITLE
Crash with MapAtlasesClientConfig

### ISSUE THREAD

**Issue by LeoDemitori** [lanAnderson/SeasonInfo#65]
Client crashing after world loading.

[SHUD_logs.txt](https://github.com/lanAnderson/SeasonHUD/files/13861983/SHUD_logs.txt)
[SHUD_crash.txt](https://github.com/lanAnderson/SeasonHUD/files/13861985/SHUD_crash.txt)

Mod Version **1.7.8**

**Comment by lanAnderson** [comment]
Looks like you need to update MapAtlases, you're still on 2.6.0.  It got a rewrite at the end of December and that is the version currently supported.
