### ISSUE TITLE
Crash after adding this mod in my 1.20.1 modpack

### ISSUE THREAD

**Issue by vico93** [lanAnderson/SeasonInfo#68]
Basically, i'm having [this crash](https://gist.github.com/vico93/643015303c4c6b64489680d280e8d2ba) after trying to add SeasonHUD (and ForgeConfigApiPort 8.0.0) to my modpack.

MC: 1.20.1
Fabric Loader: 0.15.6
Fabric API: 0.91.0

**Comment by lanAnderson** [comment]
Update to the latest version of MapAtlases and it should fix it. It looks like it's only available on CurseForge, and not Modrinth.

**Comment by vico93** [comment]
> Update to the latest version of MapAtlases and it should fix it. It looks like it's only available on CurseForge, and not Modrinth.

But isnt the latest version of MapAtlases a fork? I tried it when i was on 1.20.4 but didn't like the changes made to that mod.

Btw, thanks for the clarification!

**Comment by lanAnderson** [comment]
I think the person who handles the Forge port took over the project and is updating it going forward. If you want to still use the 2.6.0, then version 1.7.6 of my mod should work, as I updated to supporting the new MapAtlases changes in 1.7.7
