### ISSUE TITLE
Season HUD is not hidden with the minimap when using a spyglass

### ISSUE THREAD

**Issue by NeuTraLZero** [lanAnderson/SeasonInfo#69]
This is with JourneyMap

![image](https://github.com/lanAnderson/SeasonHUD/assets/43245485/91e84bfe-44da-4f76-9d4a-3c3f6c9ef3c7)
![image](https://github.com/lanAnderson/SeasonHUD/assets/43245485/0e903bf1-b2dd-4dee-ab4c-53d720cda07f)

**Comment by lanAnderson** [comment]
Should be fixed in version 1.7.11
