### ISSUE TITLE
[Bug] SeasonHUD cannot display if Journeymap's minimap has hiddien before game startup.

### ISSUE THREAD

**Issue by Hakuyako** [lanAnderson/SeasonInfo#70]
When setting Journeymap's minimap to disable in default, or just hidden the minimap through shortcut key before turn off the game, seasonHUD will not display anymore even if you turn on the minimap in game.

Even though setting 'enable_show_minimap_hidden' to ture, seasonHUD still doesn't display in game anymore.

Game version: 1.20.1
Forge version: 47.1.47
Journeymap version: 1.20.1-5.9.18
SeasonHUD version: .20.1-1.7.11

**Comment by Hakuyako** [comment]
I also find another problem when using this seasonHUD with journeymap, the HUD will not turn on and off with the minimap.
When turn off the minimap, the hud stays on the screen, if scaling the game window at this time, the HUD will float in place.

**Comment by lanAnderson** [comment]
Fixed in 1.7.12 (uploading now)
