### ISSUE TITLE
[Mod Support Request] TechPro424's fork of MapAtlases

### ISSUE THREAD

**Issue by vico93** [lanAnderson/SeasonInfo#72]
Hello!

Don't know if this is needed for forks, but @TechPro424 made a fork of the original MapAtlases for 1.20.4, so if you could add support for this too, thank you so much.

https://github.com/TechPro424/MapAtlases

_PS.: With "original" i mean, different from the other fork for 1.20.1 (the author refused to port to 1.20.4 due to "low downloads"), this fork have the original mod features, without changing anything AFAIK._

**Comment by lanAnderson** [comment]
Yeah, should be able to get something working using the code before the previous fork

**Comment by lanAnderson** [comment]
Added to the 1.20.4 version in v1.8.0

**Comment by TechPro424** [comment]
Thanks for taking the time to support my fork!
However,
- that fork was only made so I could PR fixes 
- it needs to be updated for 1.20.6 anyway
- the original mod has been updated to support 1.20.4
