### ISSUE TITLE
Caused Out of Bounds Exception w/Xaero's Minimap

### ISSUE THREAD

**Issue by burghenby** [lanAnderson/SeasonInfo#77]
**Describe the issue**
- I attempted to switch the setting from "Show Days" to "Show with Month" and my game crashed. At first I though the issue was with Xaero's minimap as that was what the crash log showed me... 

> java.lang.RuntimeException: Xaero's Minimap (1.19.1_24.0.3) has crashed! Please report here: bit.ly/XaeroMMIssues

- ...However, I hadn't changed anything with minimap config. I hadn't even gone into the config! I attempted to load my game again, this time with a new save specifically, and the game locked up upon load with the HUD scrunched up.
![image_2024-04-08_232807950](https://github.com/lanAnderson/SeasonHUD/assets/158222215/33a3308b-d544-44b9-9815-6e1e3c01401a)
-  I observed that the SeasonHUD was not displaying with the minimap and suspected that, perhaps, the option was not playing nice with Xaero's minimap. I force-closed my game and upon reload I changed the SeasonHUD via the main menu to not integrate with minimap so that it would display alone and set it to display in the top-right corner, where the minimap was not. I watched the livelog scroll as the save loaded and that is where I saw the messages referring to an out-of-bounds issue. When I switched back to my game window it was paused, but the HUD beyond the pause was the same as before. Unpausing resulted in a locked-up game again.
- After force-closing again, I reloaded and reverted the SeasonHUD back to what I had before (Integrated to minimap, Show Days) and then loaded the save again. This time is loaded without issue.
- Unfortunately I did not have the foresight to save the live-logs from the two lock-ups, otherwise I would share. I do, however, have the initial crash from when I initially changed the setting. (Full attached at bottom)

> Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[?:?] {}
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source) ~[?:?] {}
	at jdk.internal.util.Preconditions.checkIndex(Unknown Source) ~[?:?] {}
	at java.util.Objects.checkIndex(Unknown Source) ~[?:?] {re:mixin}
	at java.util.ArrayList.get(Unknown Source) ~[?:?] {re:mixin}
	at club.iananderson.seasonhud.impl.minimaps.XaeroInfoDisplays.lambda$static$0(XaeroInfoDisplays.java:25) ~[seasonhud-forge-1.19.x-1.7.18.jar%23537!/:1.7.18] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}

**Minecraft Version**
- 1.19.2

**Mod Version**
- 1.7.18

**Modloader(Fabric/Forge/NeoForge)**
- Forge

**Modloader Version**
- 43.3.0

**Additional Info (Crashlog/Modlist)**
- [crash-2024-04-08_22.50.43-client.txt](https://github.com/lanAnderson/SeasonHUD/files/14913091/crash-2024-04-08_22.50.43-client.txt)

**Comment by lanAnderson** [comment]
Thanks for the detailed report! The "Show with Month" is actually only for the Fabric version, since it's a feature of FabricSeasons. I have it hidden from selecting in the ingame menu, but didn't notice the config still took the value.

I was able to find a way to stop it from showing as an option in the Forge config, and should be fixed in the next updated

**Comment by burghenby** [comment]
Ah, gotcha! I use MrCrayfish's mod "Configured" so that is how I changed the config in the first place., just for reference. Thank you for the response!
