### ISSUE TITLE
Map Atlas 1.20.4 compatibility

### ISSUE THREAD

**Issue by Jack-Chronicle** [lanAnderson/SeasonInfo#79]
**Describe the issue**
- Trying to load the game with SeasonHUD and Map Atlases installed causes it to not load, with the error -
 "Mod 'SeasonHUD' 1.7.19 is incompatible with any version before 2.7.0 of mod 'Map Atlases', but a matching version is present: 2.6.1!

**Minecraft Version**
- 1.20.4

**Mod Version**
- 1.7.19

**Modloader(Fabric/Forge/NeoForge)**
- Fabric

**Modloader Version**
- 0.15.11

**Comment by lanAnderson** [comment]
I'll take a look at it this weekend. It looks like the original author uploaded a version for 1.20.4 so I'll need to go back and test some things out

**Comment by lanAnderson** [comment]
Added to the 1.20.4 version in v1.8.0
