### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zc1108aaa** [lanAnderson/SeasonInfo#82]
[crash-2024-05-27_12.38.43-client.txt](https://github.com/lanAnderson/SeasonHUD/files/15450865/crash-2024-05-27_12.38.43-client.txt)
1
[latest.log](https://github.com/lanAnderson/SeasonHUD/files/15450866/latest.log)

**Comment by lanAnderson** [comment]
It looks like you are using MapAtlases 2.6.0 still. You'll either need to upgrade to the latest version [here](https://legacy.curseforge.com/minecraft/mc-mods/map-atlases/files/all) or downgrade SeasonHud to around v1.7.6, since that was the last version to support the older version
