### ISSUE TITLE
Date display resetting to Spring when Summer starts

### ISSUE THREAD

**Issue by AtlasOrigins** [lanAnderson/SeasonInfo#86]
**Describe the issue**
- . Date display under minimap after the 8th day rather than going to summer the date appears to reset back to Early Spring day 1

**Minecraft Version**
- . 1.20.6

**Mod Version**
- .1.8.1, 1.8.2

**Modloader(Fabric/Forge/NeoForge)**
- .Fabric

**Modloader Version**
- .Fabric 1.20.6

**Additional Info (Crashlog/Modlist)**
- .Xaeros minimap 24.1.4 and Worldmap 1.38.6, Serene Seasons 9.4.0.4, BetterF3 10.0.1

**Comment by lanAnderson** [comment]
Do you happen to be using the /time command to set to day? I'm having trouble replicating it when letting it naturally switch from one day to another, but using "/time day" seems to be causing issues with SereneSeasons and subtracts time.

**Comment by AtlasOrigins** [comment]
No during the time using this mod I have let the time run without any manipulation other than sleeping from the start of a new world.

**Comment by lanAnderson** [comment]
Can you see if it is still happening with Serene Seasons 9.4.0.5? They merged my fix top handle if negative time gets through
