### ISSUE TITLE
Spanish translations

### ISSUE THREAD

**Issue by Caapri** [lanAnderson/SeasonInfo#89]
Hi, how can i help you to add spanish translations? i use this mod in my personal modpack and i want to have this mod in spanish if it's possible please. Thank you in advance.

**Comment by lanAnderson** [comment]
Hi,

You can make a pull request with new translation file added (they are located in "common/src/main/resources/assets/seasonhud/lang") or here is the latest english version of the file and you can make the changes to it and send it back. You'll just replace the second part of each line with the spanish translation for it, then name the file the locale code for the translation. You can find that [here](https://minecraft.fandom.com/wiki/Language) under the "Locale Code > In-Game" heading. 

[en_us.json](https://github.com/user-attachments/files/15812224/en_us.json)

**Comment by Caapri** [comment]
I have done it locally and I have tried to upload the branch with the spanish translations file but I don't have permissions. I pass you here the file or give me permission to commit to this repository? Thanks in advance.

**Comment by lanAnderson** [comment]
If you wanna just upload it in a comment, I can grab that and include it next update

**Comment by Caapri** [comment]
Here it is. Thank you.

[es_es.json](https://github.com/user-attachments/files/15829457/es_es.json)

**Comment by lanAnderson** [comment]
Thank you! I'll include that in version 1.8.4, that should be out today
