### ISSUE TITLE
SeasonHUD incorectly marked as compatible with just SereneSeasons 10.0.0.0

### ISSUE THREAD

**Issue by MimzyFang** [lanAnderson/SeasonInfo#91]
**Describe the issue**

- SeasonHUD is only compatible with 10.0.0.0 of SereneSeasons though when overwriting this it still works with 10.0.0.2 please don's mark the compat that strictly

**Minecraft Version**

- 1.21

**Mod Version**

- 1.8.4

**Modloader(Fabric/Forge/NeoForge)**

- Fabric

**Modloader Version**

- 0.15.11

**Additional Info (Crashlog/Modlist)**

```
[15:25:18] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'SereneSeasons' (sereneseasons) 10.0.0.2 with version 10.0.0.0.
More details:
	 - Mod 'SeasonHUD' (seasonhud) 1.8.4 requires version 10.0.0.0 of mod 'SereneSeasons' (sereneseasons), but only the wrong version is present: 10.0.0.2!
```

**Comment by lanAnderson** [comment]
Oops, meant to mark that as any version instead. Will be fixed in 1.8.5
