### ISSUE TITLE
SeasonHUD 1.8.5 Mod Loading Issue

### ISSUE THREAD

**Issue by MysticcWaters** [lanAnderson/SeasonInfo#92]
**Describe the issue**

- When loading up SeasonHUD 1.8.5 with Serene Seasons, a mod loading error occurs, stating that "Mod seasonhud requires requires sereneseasons" even though Serene Seasons is downloaded.

**Minecraft Version**

- 1.20.1

**Mod Version**

- 1.8.5

**Modloader(Fabric/Forge/NeoForge)**

- NeoForge

**Modloader Version**

- 47.1.106

**Additional Info (Crashlog/Modlist)**

![SeasonsHUD Bug](https://github.com/lanAnderson/SeasonHUD/assets/130418925/74cf600c-e50b-4a30-b934-cc8727ac18a4)

**Comment by lanAnderson** [comment]
Fixed in 1.8.6
