### ISSUE TITLE
Crash Upon World Loading

### ISSUE THREAD

**Issue by UnknownSerhan** [lanAnderson/SeasonInfo#94]
**Describe the issue**

- When loading up the game with the latest JourneyMap version (6.0.0 - beta.7), the game crashes when you load into a world.

**Minecraft Version**

- 1.21

**Mod Version**

- 1.8.6

**Modloader(Fabric/Forge/NeoForge)**

- NeoForge

**Modloader Version**

- 21.0.20

**Additional Info (Crashlog/Modlist)**

[crash-2024-06-20_21.29.05-client.txt](https://github.com/user-attachments/files/15918536/crash-2024-06-20_21.29.05-client.txt)

**Comment by lanAnderson** [comment]
Thanks, I'll take a look later today to see what the changes were.

**Comment by lanAnderson** [comment]
Should be fixed in 1.8.7
