### ISSUE TITLE
1.21 NEOFORGE CRASH ON START

### ISSUE THREAD

**Issue by Hiusi** [lanAnderson/SeasonInfo#98]
I update season HUD and the modloader, but it crashes on startup

**Minecraft Version**

- .1.21

**Mod Version**

- .1.9.2

**Modloader(Fabric/Forge/NeoForge)**

- .Neoforge

**Modloader Version**

- .21.0.95-beta

**Additional Info (Crashlog/Modlist)**
[latest.log](https://github.com/user-attachments/files/16241077/latest.log)
- .

**Comment by lanAnderson** [comment]
Should be fixed in 1.9.3
